<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pradeeps-MacBook-Pro.local" failures="2" tests="26" name="com.myapp.spring.NumberSubscriberVerification" time="0.613" errors="0" timestamp="2022-11-24T14:36:06 IST" skipped="15">
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec213_blackbox_failingOnSignalInvocation" time="0.004">
    <skipped/>
  </testcase> <!-- untested_spec213_blackbox_failingOnSignalInvocation -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec213_blackbox_onNext_mustThrowNullPointerExceptionWhenParametersAreNull" time="0.012">
    <failure message="onNext(null) did not throw NullPointerException expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: onNext(null) did not throw NullPointerException expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.reactivestreams.tck.SubscriberBlackboxVerification$10.run(SubscriberBlackboxVerification.java:362)
at org.reactivestreams.tck.SubscriberBlackboxVerification.blackboxSubscriberWithoutSetupTest(SubscriberBlackboxVerification.java:449)
at org.reactivestreams.tck.SubscriberBlackboxVerification.required_spec213_blackbox_onNext_mustThrowNullPointerExceptionWhenParametersAreNull(SubscriberBlackboxVerification.java:345)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- required_spec213_blackbox_onNext_mustThrowNullPointerExceptionWhenParametersAreNull -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec314_blackbox_cancelMayCauseThePublisherToShutdownIfNoOtherSubscriptionExists" time="0.001">
    <skipped/>
  </testcase> <!-- untested_spec314_blackbox_cancelMayCauseThePublisherToShutdownIfNoOtherSubscriptionExists -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec203_blackbox_mustNotCallMethodsOnSubscriptionOrPublisherInOnComplete" time="0.016"/>
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec308_blackbox_requestMustRegisterGivenNumberElementsToBeProduced" time="0.002">
    <skipped/>
  </testcase> <!-- untested_spec308_blackbox_requestMustRegisterGivenNumberElementsToBeProduced -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec316_blackbox_requestMustNotThrowExceptionAndMustOnErrorTheSubscriber" time="0.008">
    <skipped/>
  </testcase> <!-- untested_spec316_blackbox_requestMustNotThrowExceptionAndMustOnErrorTheSubscriber -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec213_blackbox_onSubscribe_mustThrowNullPointerExceptionWhenParametersAreNull" time="0.010"/>
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec209_blackbox_mustBePreparedToReceiveAnOnCompleteSignalWithoutPrecedingRequestCall" time="0.030"/>
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec210_blackbox_mustBePreparedToReceiveAnOnErrorSignalWithPrecedingRequestCall" time="0.008"/>
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec205_blackbox_mustCallSubscriptionCancelIfItAlreadyHasAnSubscriptionAndReceivesAnotherOnSubscribeSignal" time="0.143">
    <failure message="Subscriber org.reactivestreams.tck.SubscriberWhiteboxVerification$BlackboxSubscriberProxy@7e990ed7 illegally called `subscription.request(10)`!" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Subscriber org.reactivestreams.tck.SubscriberWhiteboxVerification$BlackboxSubscriberProxy@7e990ed7 illegally called `subscription.request(10)`!
at org.testng.Assert.fail(Assert.java:99)
at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:222)
at org.reactivestreams.tck.SubscriberBlackboxVerification$4$1.request(SubscriberBlackboxVerification.java:219)
at com.myapp.spring.NumberSubscriber.onSubscribe(NumberSubscriber.java:13)
at org.reactivestreams.tck.SubscriberWhiteboxVerification$BlackboxSubscriberProxy.onSubscribe(SubscriberWhiteboxVerification.java:610)
at org.reactivestreams.tck.SubscriberBlackboxVerification$4.<init>(SubscriberBlackboxVerification.java:215)
at org.reactivestreams.tck.SubscriberBlackboxVerification.required_spec205_blackbox_mustCallSubscriptionCancelIfItAlreadyHasAnSubscriptionAndReceivesAnotherOnSubscribeSignal(SubscriberBlackboxVerification.java:212)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- required_spec205_blackbox_mustCallSubscriptionCancelIfItAlreadyHasAnSubscriptionAndReceivesAnotherOnSubscribeSignal -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec202_blackbox_shouldAsynchronouslyDispatch" time="0.003">
    <skipped/>
  </testcase> <!-- untested_spec202_blackbox_shouldAsynchronouslyDispatch -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec212_blackbox_mustNotCallOnSubscribeMoreThanOnceBasedOnObjectEquality" time="0.009">
    <skipped/>
  </testcase> <!-- untested_spec212_blackbox_mustNotCallOnSubscribeMoreThanOnceBasedOnObjectEquality -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec204_blackbox_mustConsiderTheSubscriptionAsCancelledInAfterRecievingOnCompleteOrOnError" time="0.001">
    <skipped/>
  </testcase> <!-- untested_spec204_blackbox_mustConsiderTheSubscriptionAsCancelledInAfterRecievingOnCompleteOrOnError -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec207_blackbox_mustEnsureAllCallsOnItsSubscriptionTakePlaceFromTheSameThreadOrTakeCareOfSynchronization" time="0.002">
    <skipped/>
  </testcase> <!-- untested_spec207_blackbox_mustEnsureAllCallsOnItsSubscriptionTakePlaceFromTheSameThreadOrTakeCareOfSynchronization -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec310_blackbox_requestMaySynchronouslyCallOnNextOnSubscriber" time="0.003">
    <skipped/>
  </testcase> <!-- untested_spec310_blackbox_requestMaySynchronouslyCallOnNextOnSubscriber -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec201_blackbox_mustSignalDemandViaSubscriptionRequest" time="0.069"/>
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec315_blackbox_cancelMustNotThrowExceptionAndMustSignalOnError" time="0.001">
    <skipped/>
  </testcase> <!-- untested_spec315_blackbox_cancelMustNotThrowExceptionAndMustSignalOnError -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec213_blackbox_onError_mustThrowNullPointerExceptionWhenParametersAreNull" time="0.006"/>
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec301_blackbox_mustNotBeCalledOutsideSubscriberContext" time="0.002">
    <skipped/>
  </testcase> <!-- untested_spec301_blackbox_mustNotBeCalledOutsideSubscriberContext -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec208_blackbox_mustBePreparedToReceiveOnNextSignalsAfterHavingCalledSubscriptionCancel" time="0.002">
    <skipped/>
  </testcase> <!-- untested_spec208_blackbox_mustBePreparedToReceiveOnNextSignalsAfterHavingCalledSubscriptionCancel -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec203_blackbox_mustNotCallMethodsOnSubscriptionOrPublisherInOnError" time="0.199"/>
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec206_blackbox_mustCallSubscriptionCancelIfItIsNoLongerValid" time="0.003">
    <skipped/>
  </testcase> <!-- untested_spec206_blackbox_mustCallSubscriptionCancelIfItIsNoLongerValid -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec209_blackbox_mustBePreparedToReceiveAnOnCompleteSignalWithPrecedingRequestCall" time="0.037"/>
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec311_blackbox_requestMaySynchronouslyCallOnCompleteOrOnError" time="0.003">
    <skipped/>
  </testcase> <!-- untested_spec311_blackbox_requestMaySynchronouslyCallOnCompleteOrOnError -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="untested_spec211_blackbox_mustMakeSureThatAllCallsOnItsMethodsHappenBeforeTheProcessingOfTheRespectiveEvents" time="0.011">
    <skipped/>
  </testcase> <!-- untested_spec211_blackbox_mustMakeSureThatAllCallsOnItsMethodsHappenBeforeTheProcessingOfTheRespectiveEvents -->
  <system-out/>
  <testcase classname="com.myapp.spring.NumberSubscriberVerification" name="required_spec210_blackbox_mustBePreparedToReceiveAnOnErrorSignalWithoutPrecedingRequestCall" time="0.028"/>
  <system-out/>
</testsuite> <!-- com.myapp.spring.NumberSubscriberVerification -->
